# This rule is not used by the project kubeinfer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ml.kubeinfer.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeinfer
    app.kubernetes.io/managed-by: kustomize
  name: inferencejob-viewer-role
rules:
- apiGroups:
  - ml.kubeinfer.io
  resources:
  - inferencejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.kubeinfer.io
  resources:
  - inferencejobs/status
  verbs:
  - get
