# This rule is not used by the project kubeinfer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ml.kubeinfer.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeinfer
    app.kubernetes.io/managed-by: kustomize
  name: inferencejob-admin-role
rules:
- apiGroups:
  - ml.kubeinfer.io
  resources:
  - inferencejobs
  verbs:
  - '*'
- apiGroups:
  - ml.kubeinfer.io
  resources:
  - inferencejobs/status
  verbs:
  - get
