# This rule is not used by the project kubeinfer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ml.kubeinfer.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeinfer
    app.kubernetes.io/managed-by: kustomize
  name: inferencejob-editor-role
rules:
- apiGroups:
  - ml.kubeinfer.io
  resources:
  - inferencejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ml.kubeinfer.io
  resources:
  - inferencejobs/status
  verbs:
  - get
